version: "3.9"
services:
  node-das:
    image: vicentevicedo/das
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
#    command: tail -F /dev/null
    tty: true
    networks:
      - frontend
      - backend
    links:
      - "db:database"
  angular-das:
    image: angular/ngcontainer
#    network:
#      - frontend
  db:
    image: mysql:latest
#    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dasuser'
      MYSQL_PASSWORD: 'daspassword'
      MYSQL_ROOT_PASSWORD: 'Putincabron69'
    volumes:
       - db-data:/var/lib/mysql
    networks:
       - backend
volumes:
  db-data:
networks:
  frontend:
  backend:
